devices:
  - id: paczek
    name: "Pączek"
    type: shelly_plug
    host: 192.168.1.87
    aliases:
      - pączek
      - pączka
      - pączku
      - pączkiem
      - donut
      - lampka
      - światło
    misheard:
      - ponczek
      - bądźka
      - wątponczka

  - id: ps5
    name: "PlayStation"
    type: ps5
    host: 192.168.1.36
    options:
      host_id: 68286C32BF27
    aliases:
      - playstation
      - plejstejszyn
      - ps5
      - konsola
      - console
    misheard:
      - plej stejszyn
      - plajstejszyn
